name: nq
version: 2.5.3
date: 2016-03-08
description: |
    Nilpotent Quotients of Finitely Presented Groups

authors:
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.4"

needed-pkgs:
    - name: "polycyclic"
      version: "1.0"
      url: "https://gap-packages.github.io/polycyclic/"

suggested-pkgs:
    - name: "GAPDoc"
      version: "1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-packages.github.io/nq/
readme: README
packageinfo: http://gap-packages.github.io/nq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/nq/releases/download/v2.5.3/nq-2.5.3.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/nq/releases/download/v2.5.3/nq-2.5.3.tar.bz2

abstract: |
    This package provides access to the ANU nilpotent quotient program for computing nilpotent factor groups of finitely presented groups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
