name: nq
version: 2.5
date: 01/04/2014
description: Nilpotent Quotients of Finitely Presented Groups

authors:
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math.php

GAP: ">= 4.4"

needed-pkgs:
    - name: "polycyclic"
      version: "1.0"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/"

suggested-pkgs:
    - name: "GAPDoc"
      version: "1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-system.github.io/nq/
readme: http://gap-system.github.io/nq/README
packageinfo: http://gap-system.github.io/nq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/nq/releases/download/v2.5/nq-2.5.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-system/nq/releases/download/v2.5/nq-2.5.tar.bz2

abstract: This package provides access to the ANU nilpotent quotient program for computing nilpotent factor groups of finitely presented groups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
